//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContainerManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string Location { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public int TotalWeight { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
